sudo: false

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2

script: "bundle exec rake --trace"

notifications:
  recipients:
    - nahi@ruby-lang.org

matrix:
  allow_failures:
    - rvm: jruby-head # https://github.com/jruby/jruby/issues/3577
    - rvm: rbx-2
    - rvm: jruby-18mode # NoMethodError: undefined method `world_writable?' for #<File::Stat:0x433e0608>
