sudo: false

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-head

script: "bundle exec rake --trace"

notifications:
  recipients:
    - nahi@ruby-lang.org

matrix:
  allow_failures:
    - rvm: jruby-head
